### ISSUE TITLE
Bootstrap is failing while installing capsule server 

### ISSUE THREAD

**Issue by ganeshpayelkar** [RedHatSatellite/capsule-maintain#12]
If you have provisioned system from satellite and unregistered it then you may face this issue.

TASK [bootstrap : Run bootstrap.py] **************************************************
Wednesday 09 May 2018  16:24:48 -0400 (0:00:00.613)       0:00:20.365 ********* 
fatal: [caps2.satellite6.local]: FAILED! => {"changed": true, "cmd": ["/tmp/bootstrap.py", "--server=testday2.satellite6.local", "--organization=Default_Organization", "--activationkey=ak-capsule-7", "--skip-foreman"], "delta": "0:00:00.126536", "end": "2018-05-09 20:24:48.629928", "msg": "non-zero return code", "rc": 1, "start": "2018-05-09 20:24:48.503392", "stderr": "", "stderr_lines": [], "stdout": "Foreman Bootstrap Script\nThis script is designed to register new systems or to migrate an existing system to a Foreman server with Katello\n[NOTIFICATION], [2018-05-09 20:24:48], [This system is not registered to RHN. Attempting to register via subscription-manager] \n[NOTIFICATION], [2018-05-09 20:24:48], [A Katello CA certificate is already installed. Assuming system is registered] \n[NOTIFICATION], [2018-05-09 20:24:48], [To override this behavior, run the script with the --force option. Exiting.] ", "stdout_lines": ["Foreman Bootstrap Script", "This script is designed to register new systems or to migrate an existing system to a Foreman server with Katello", "[NOTIFICATION], [2018-05-09 20:24:48], [This system is not registered to RHN. Attempting to register via subscription-manager] ", "[NOTIFICATION], [2018-05-09 20:24:48], [A Katello CA certificate is already installed. Assuming system is registered] ", "[NOTIFICATION], [2018-05-09 20:24:48], [To override this behavior, run the script with the --force option. Exiting.] "]}
...ignoring

**Comment by sthirugn** [comment]
Current workaround is to use `--force` in the bootstrap.py command in `roles/bootstrap/tasks/main.yml` in task `Run bootstrap.py`
